/**
 * Masque terre/mer équirectangulaire 360×180 (1 bit par cellule, base64).
 * Sert à placer les points du globe uniquement sur les continents.
 */
export const LAND_W = 360;
export const LAND_H = 180;

const LAND_B64 =
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/8AAAH//+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//+B" +
  "//////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeBP/wf///////gAAAAAAAAAAAAAAAAADgAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAP4/4Af//////8AAAAAAAAAAAAAAAAAABwAAAAAAAAAAAAAAAAAAAAAAAAAAADD/wH///////4AAAAATgAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF+AH///////4AAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADz" +
  "//////4AAAAAAAAAAAAAAAAAAAB+AAAAAAAAAAAAAAAAAAAAAADxAMDAAAAAP/////8AAAAAAAAAAAABgAAAAH//+AAAAwAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAD/////4AAAAAAAAAAAAOAAAAH///wAAAAAAAAAAAAAAAAAAAAP4AAEcAAAAAD/////wAAAAAAAAAAAAY" +
  "AAAAP//+AAAAAAAAAAAAAAAAAAAAAfPAYOQZ4gAAB////+AAAAAAAAAAAABgADAD///////4AAAAAAAAAAAAAAAAAEP/4AQd/8AA" +
  "AP///+gAAAAAAAAAAABgAHI5///////4AP/AAAAAAAADgAAAAAAf8A4H//gAAH///8AAAAAAAAAAAAAAAPP+///////+///z4AAA" +
  "AAA///wAOAA/+AMBwP8AAH///+AAAAAAAf/gAAAAAPP/////////////8AGAAAD////v//+AACOhwB8AAH///AAAAAAAB///gAAA" +
  "fnm///////////////3/8AB////////EeHfzwA/gAf//wAAAAAAAH///8Af///H/////////////////+wAf///////////9AB/8" +
  "Af//gAAAAAAAP//4cF///+P/////////////////DwP////////////4AD8QAP/wAAD4AAAAf8f8B///////////////////////" +
  "AAAf///////////zgD/AAP/gAAP4AAAA/4f+D//////////////////////8AAAf//////////+AAA/gAH/gAAAAAAAD/h//////" +
  "///////////////////8AAH///////////4AAAAAAD/AAAAAAAAf/D///////////////////////n/wAAH///////////wAA/AA" +
  "AB+AAAAAAAB/+D//////////////////////DP+AAAD/9x////////gAAfwAAAGAAAAAAAB/+Dx////////////////////+AOAA" +
  "AAA/wAB///////gAAfwQAAAAAAAAAAA//AB//////////////////+AMAgAAAAABwAAP//////wAA/44AAAAAAAAAAAQ+A//////" +
  "/////////////4AADAAAAAABAAAB//////4AAP/8AAAAAAAAAQAA8Af//////////////////gAAPAAAAAAAAAAB///////gAP/+" +
  "AAAAAAAAA4AEcD///////////////////AAAfgAAAAAAAAAAf//////4Af/+AAAAAAAAAcAEAH//////////////////8AAA/AAA" +
  "AAAAAAAAP///////h///wAAAAAAADGAEAH//////////////////8AAA8AAAAAAAAAAAP///////x///4AAAAAAAHHAH////////" +
  "////////////+QAA4AAAAAAAAAAAD///////w///8AAAAAAAGPg//////////////////////6AAQAAAAAAAAAAAD///////5///" +
  "wAAAAAAAAPh//////////////////////6AAAAAAAAAAAAAAB//////////fAAAAAAAAAAP//////////////////////wAAAAAA" +
  "AAAAAAAAAn////////8AMAAAAAAAAAf//////////////////////wAAAAAAAAAAAAAAAH////////5gPAAAAAAAAD///////6B/" +
  "/////////////wAAAAAAAAAAAAAAAP/////////gAAAAAAAAAD///////8Af/////////////gAAAAAAAAAAAAAAAP/////////g" +
  "AAAAAAAAAB/////uH4Af/////////////AAAAAAAAAAAAAAAAP/////////YAAAAAAAAAB//P//CP4AP////////////+AAAAAAA" +
  "AAAAAAAAAP////////8QAAAAAAAAAB//H/+AH8A/////////////8AAAAAAAAAAAAAAAAP////////gAAAAAAAAAAB5hh/8AD8D/" +
  "////////////4DAAAAAAAAAAAAAAAP////////gAAAAAAAAAH/4Awf8AA+B/////+//////8AAAAAAAAAAAAAAAAAP////////AA" +
  "AAAAAAAAD/wAYP8GA/Af///////////8AAAAAAAAAAAAAAAAAP///////8AAAAAAAAAAD/AAGOB///gf//////////P4AAAAAAAA" +
  "AAAAAAAAAH///////4AAAAAAAAAAH/AAAGH///Af/////////+BgAMAAAAAAAAAAAAAAAH///////wAAAAAAAAAAH+AAAGH///g/" +
  "/////////4AwAIAAAAAAAAAAAAAAAD///////gAAAAAAAAAAD8AAACD///g//////////+AYAYAAAAAAAAAAAAAAAB///////wAA" +
  "AAAAAAAAAAG8AAAM//4///////////gYBwAAAAAAAAAAAAAAAB///////wAAAAAAAAAAAA/+AAAA/////////////+AYDwAAAAAA" +
  "AAAAAAAAAAf//////AAAAAAAAAAAA//cAAAA/////////////+AAUAAAAAAAAAAAAAAAAAH/////+AAAAAAAAAAAB//8AAAA////" +
  "//////////AAAAAAAAAAAAAAAAAAAAH/////4AAAAAAAAAAAH///AAAB//////////////gAAAAAAAAAAAAAAAAAAACf////4AAA" +
  "AAAAAAAAH///4PgB//////////////gAACAAAAAAAAAAAAAAAACf///jwAAAAAAAAAAAH////P5///////////////gAAAAAAAAA" +
  "AAAAAAAAAAAP//gAYAAAAAAAAAAAP/////z///H///////////wAAAAAAAAAAAAAAAAAAAAH/+AAIAAAAAAAAAAAf//////7//D/" +
  "//////////gAAAAAAAAAAAAAAAAAAAAj/8AAIAAAAAAAAAAA///////4//h///////////AAAAAAAAAAAAAAAAAAAAAB/8AAMAAA" +
  "AAAAAAAB///////8f/wH//////////AAAAAAAAAAAAAAAAAAAAAA/8AAAAAAAAAAAAAD///////8f/wAYf///////+AAAAAAAAAA" +
  "AAAAAAAAAAAAf8AAAAAAAAAAAAAH///////+P/4QAP///////8AAAAAAAAAAAAAAAAAAAAAAP8AAAAAAAAAAAAAH///////+H//4" +
  "AH///////4AAAAAAAAAAAAAAAAAAAAAAH8AAAAAAAAAAAAAP////////H//+AD///v//+AAAAAAAAAAAAAAAAAAAAAAAH8AAAAAA" +
  "AAAAAAAP////////n//+ADf/4P//IAAAAAAAAAAAAAAAAAAAAAAAH+A4AQAAAAAAAAAP////////j//8AAf/wH/8AAAAAAAAAAAA" +
  "AAAAAAAAAAAAH+AwAAAAAAAAAAAP////////h//4AAf/gD/8AAAAAAAAAAAAAAAAAAAAAAAAB/BwAAwAAAAAAAAP////////w//w" +
  "AAf/AB/8AAAAAAAAAAAAAAAAAAAAAAAAAf/wAAAAAAAAAAAP////////4f/gAAP+AB/8AAQAAAAAAAAAAAAAAAAAAAAAAD/gAAAA" +
  "AAAAAAAP////////4f8AAAP4ABP+AAQAAAAAAAAAAAAAAAAAAAAAAAHyAAAAAAAAAAAP////////4f4AAAPwAAP/AAgAAAAAAAAA" +
  "AAAAAAAAAAAAAAD/AAAAAAAAAAAf////////8fgAAAHwAAP/gAAAAAAAAAAAAAAAAAAAAAAAAAAfAAAAAAAAAAAP////////9MAA" +
  "AAHwAAF/gAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAAAP/////////gAAAAHwAAEfgAAAAAAAAAAAAAAAAAAAAAAAAAADAAAA" +
  "AAAAAAAH/////////gAAAADwAAAfgAAAAAAAAAAAAAAAAAAAAAAAAAABAHcAAAAAAAAD/////////x4AAADgAAAGAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAgHf8AAAAAAAB//////////4AAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/+AAAAAAAB//////////wA" +
  "AAAIAAEAAABAAAAAAAAAAAAAAAAAAAAAAAAAA///gAAAAAAA//////////gAAAAIAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAf//" +
  "wAAAAAAAP/x///////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//+AAAAAAAH+A///////AAAAAAAABAAMAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAf///wAAAAAAAAAH//////AAAAAAAAxgAcAAAAAAAAAAAAAAAAAAAAAAAAAAAf///4AAAAAAAAAD/////+AA" +
  "AAAAAAZgA4AAAAAAAAAAAAAAAAAAAAAAAAAAA////4AAAAAAAAAD/////8AAAAAAAAMgD4AAAAAAAAAAAAAAAAAAAAAAAAAAA///" +
  "/8AAAAAAAAAD/////wAAAAAAAAHAH8AAAAAAAAAAAAAAAAAAAAAAAAAAB////8AAAAAAAAAD/////gAAAAAAAADgf4AAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAD////+AAAAAAAAAD/////AAAAAAAAADgP4AAAAAAAAAAAAAAAAAAAAAAAAAAD/////wAAAAAAAAD////+AAA" +
  "AAAAAABwPwgAwAAAAAAAAAAAAAAAAAAAAAAAD/////4AAAAAAAAD////8AAAAAAAAAB4HxgARgAAAAAAAAAAAAAAAAAAAAAAD///" +
  "///wAAAAAAAB////8AAAAAAAAAA8AQAAL8AAAAAAAAAAAAAAAAAAAAAAH//////8AAAAAAAA////4AAAAAAAAAAcAAAAB/gAAAAA" +
  "AAAAAAAAAAAAAAAAH///////AAAAAAAAf///4AAAAAAAAAAAAAAAA/wAAAAAAAAAAAAAAAAAAAAAD///////gAAAAAAAf///4AAA" +
  "AAAAAAAAAAAAAf4AAAAAAAAAAAAAAAAAAAAAB///////gAAAAAAAf///4AAAAAAAAAAAOAAAAfYAAAAAAAAAAAAAAAAAAAAAA///" +
  "////gAAAAAAAP///4AAAAAAAAAAAAAAAAOEAAAAAAAAAAAAAAAAAAAAAA///////AAAAAAAAP///4AAAAAAAAAAAAAAAAACAAAAA" +
  "AAAAAAAAAAAAAAAAA//////+AAAAAAAAP///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////8AAAAAAAAP///8AAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/////8AAAAAAAAP///8AAAAAAAAAAAAAAA+CAAAAAAAAAAAAAAAAAAAAAAAP//" +
  "///4AAAAAAAAf///8AQAAAAAAAAAAAAD+CAAAAAAAAAAAAAAAAAAAAAAAP/////4AAAAAAAAf///8AwAAAAAAAAAAAAD8DAAAAAA" +
  "AAAAAAAAAAAAAAAAAD/////4AAAAAAAA////8BwAAAAAAAAAAAB/+DgAAAAAAAAAAAAAAAAAAAAAAA/////4AAAAAAAA////4HwA" +
  "AAAAAAAAAAD//DgAAAAAAAAAAAAAAAAAAAAAAAf////4AAAAAAAA////gHgAAAAAAAAAAAH//3wAAAAAAAAAAAAAAAAAAAAAAAP/" +
  "///wAAAAAAAAf///AHgAAAAAAAAAAAP///wAAAAAAAAAAAAAAAAAAAAAAAP////wAAAAAAAAf//+AHgAAAAAAAAAAAP///4AAAAA" +
  "AAAAAAAAAAAAAAAAAAP////gAAAAAAAAP//+AHAAAAAAAAAAAB////8AAAAAAAAAAAAAAAAAAAAAAAP////gAAAAAAAAP//+APAA" +
  "AAAAAAAAAP////+AAAAAAAAAAAAAAAAAAAAAAAP////AAAAAAAAAH//+APAAAAAAAAAAAf/////AAAAAAAAAAAAAAAAAAAAAAAP/" +
  "//wAAAAAAAAAH//+AOAAAAAAAAAAA//////gAAAAAAAAAAAAAAAAAAAAAAP///AAAAAAAAAAH//+AOAAAAAAAAAAA//////wAAAA" +
  "AAAAAAAAAAAAAAAAAAP//+AAAAAAAAAAH//4AAAAAAAAAAAAA//////4AAAAAAAAAAAAAAAAAAAAAAP//+AAAAAAAAAAH//4AAAA" +
  "AAAAAAAAA//////4AAAAAAAAAAAAAAAAAAAAAAf//+AAAAAAAAAAD//4AAAAAAAAAAAAA//////4AAAAAAAAAAAAAAAAAAAAAAf/" +
  "/+AAAAAAAAAAB//wAAAAAAAAAAAAAf/////4AAAAAAAAAAAAAAAAAAAAAAf//8AAAAAAAAAAB//gAAAAAAAAAAAAAf/////4AAAA" +
  "AAAAAAAAAAAAAAAAAAf//4AAAAAAAAAAA//AAAAAAAAAAAAAAf/////4AAAAAAAAAAAAAAAAAAAAAAf//wAAAAAAAAAAA/+AAAAA" +
  "AAAAAAAAAP/4///4AAAAAAAAAAAAAAAAAAAAAAf//gAAAAAAAAAAAf8AAAAAAAAAAAAAAP+AP//wAAAAAAAAAAAAAAAAAAAAAAf/" +
  "/gAAAAAAAAAAAfwAAAAAAAAAAAAAAP8AG//gAAAAAAAAAAAAAAAAAAAAAA//+AAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAf/gAAAA" +
  "AAAAAAAAAAAAAAAAAA//4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/AAAAAAAAAAAAAAAAAAAAAAA//4AAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAP/AAAAAAAAAAAAAAAAAAAAAAB//4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH+AAAAAAAAAAAAAAAAAAAAAAB//" +
  "gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAAAAAAAAAAAAAAAAB/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY" +
  "AAAAAAAAAAAAAAAAAB/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/gAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAEAAACAAAAAAAAAAAAAAAAAAA/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAACAAAAAAAAAAAAAAAAAAB/g" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAB/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYA" +
  "AAAAAAAAAAAAAAAAAD+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAAAAAAAAAAAD8AAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH+A" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAH4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH4AAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4A" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+AAAAAAAAAAAAAAAAAADw" +
  "AAAAAAB4HAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB+AAAAAAAAAAAAAAAAAAP8AAAA/////l////AAAAAAAAAAAAAAAAAAAAAAAAB+" +
  "AAAAAAAAAAAAAAAAAf///4AP//////////4AAAAAAAAAAAAAAAAAAAAAAAx+AAAAAAAAAAAAAAAED////4A/////////////AAAA" +
  "AAAAAAAAAAAAAAAAAB/+AAAAAAAAAAAAAAAP/////4f/////////////+AAAAAAAAAAAAAAAAAAAAB/+AAAAAAAABAP/////////" +
  "/4////////////////AAAAAAAAAAAAAAA/AAAB//AAAAAAAD//////////////////////////////wAAAAAAAAAAAAAA//8D//+" +
  "AAAAAAD//////////////////////////////+AAAAAAAAAAD//gA//////+AAAAAAv//////////////////////////////wAA" +
  "AAAAAAB/////////////AAAAAB///////////////////////////////gAAAAAAAP//////////////+AAAAH//////////////" +
  "/////////////////gAAAAABz////////////////+AAD////////////////////////////////gAAvgAf////////////////" +
  "//8A////////////////////////////////////////////////////////////////////////////////////////////////" +
  "////////////////////////////////////////////////////////////////////////////////////////////////////" +
  "////////////////////////////////////////////////////////////////////////////////////////////////////" +
  "////////////////////////////////////////////////////////////////////////////////////////////////////" +
  "////////////////////////////////////////////////////////////////////////////////////////////////////" +
  "////////////////////////////////////////////////////////////////////////////////////////////////////" +
  "////////////////////////////////////////////////////////////////////////////////////////////////////";

let bytes: Uint8Array | null = null;

function getBytes() {
  if (bytes) return bytes;
  const bin = atob(LAND_B64);
  const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i);
  bytes = arr;
  return arr;
}

/** lon en [-180,180], lat en [-90,90] -> true si terre. */
export function isLand(lon: number, lat: number) {
  const x = Math.min(LAND_W - 1, Math.max(0, Math.floor(((lon + 180) / 360) * LAND_W)));
  const y = Math.min(LAND_H - 1, Math.max(0, Math.floor(((90 - lat) / 180) * LAND_H)));
  const i = y * LAND_W + x;
  const b = getBytes()[i >> 3];
  return b !== undefined && (b & (128 >> (i & 7))) !== 0;
}
